// marketplace
let allProductsHTML = [];

document.getElementById("addProductForm").addEventListener("submit", function(e){

    e.preventDefault();

    const name = document.getElementById("name").value;
    const shop = document.getElementById("shop").value;
    const category = document.getElementById("category").value;
    const originalPrice = document.getElementById("originalPrice").value;
    const discountPrice = document.getElementById("discountPrice").value;
    const imgURL = document.getElementById("imgURL").value;
    const buyURL = document.getElementById("buyURL").value;
    const stock = document.getElementById("stock").value;
    const rating = document.getElementById("rating").value;
    const date = new Date().toLocaleDateString("id-ID");

    let stars = "";
    for(let i=0;i<rating;i++) stars += "&#11088;";

    const cardHTML = `
<div class="card" style="border-radius:8px;border:1px solid #ddd;display:inline-block;margin:15px;padding:5px;vertical-align:top;width:150px;position:relative;">

<div style="position:absolute;top:5px;left:5px;background:#ff0000;color:#fff;padding:2px 5px;font-size:11px;border-radius:4px;">
Stock: ${stock}
</div>

<img src="${imgURL}" alt="${name}" style="width:100%;border-radius:5px;">

<div style="font-weight:bold;margin-top:5px;">
${name}
</div>

<div style="font-size:12px;color:#555;">
${shop}
</div>

<div style="font-size:12px;color:#555;">
🔖 ${category}
</div>

<div style="font-weight:bold;margin-top:5px;">
Rp ${discountPrice}
<span style="font-size:12px;color:#999;text-decoration:line-through;">
Rp ${originalPrice}
</span>
</div>

<div style="font-size:11px;margin-top:4px;">
${stars} | ${date}
</div>

<a href="${buyURL}" style="display:block;background:#00bfff;color:#fff;text-align:center;padding:6px;border-radius:5px;text-decoration:none;margin-top:8px;">
Beli Sekarang
</a>

</div>`;

    const temp = document.createElement("div");
    temp.innerHTML = cardHTML;

    document.getElementById("productContainer")
    .appendChild(temp.firstElementChild);

    allProductsHTML.push(cardHTML);

    document.getElementById("outputBox").textContent =
`<div class="katalog-grid">
${allProductsHTML.join("\n")}
</div>`;

    this.reset();

});

document.getElementById("outputBox")
.addEventListener("click", function(){

    navigator.clipboard.writeText(this.textContent);

    const t = document.getElementById("toast");

    t.style.display = "block";

    setTimeout(()=>{
        t.style.display = "none";
    },1200);

});

//about
function generateAbout(){
  var nama = document.getElementById("nama").value;
  var url = document.getElementById("url").value;
  var owner = document.getElementById("owner").value;
  var deskripsi = document.getElementById("deskripsi").value;
  var email = document.getElementById("email").value;
var lang  = document.getElementById("about_language").value;

  let hasil = "";

  // =========================
  // BAHASA INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>Tentang Kami</h1>

<p>Selamat datang di <strong>${nama}</strong>!</p>

<p>${nama} adalah sebuah platform yang menyediakan ${deskripsi}. Kami berkomitmen untuk memberikan layanan terbaik dan informasi yang bermanfaat bagi pengunjung kami.</p>

<p>Situs ini didirikan dan dikelola oleh <strong>${owner}</strong>. Kami terus berupaya mengembangkan ${nama} agar menjadi lebih baik dan memberikan pengalaman terbaik bagi pengguna.</p>

<h3>Misi Kami</h3>
<p>Misi kami adalah menyediakan konten yang berkualitas, terpercaya, dan mudah diakses oleh semua orang.</p>

<h3>Visi Kami</h3>
<p>Menjadi platform yang bermanfaat dan terpercaya di internet.</p>

<h3>Kontak Kami</h3>
<p>Jika Anda memiliki pertanyaan, saran, atau ingin bekerja sama, silakan hubungi kami melalui email di <a href="mailto:${email}">${email}</a>.</p>

<p>Website: <a href="${url}" target="_blank">${url}</a></p>
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/about-us-online-generator.html" title="About Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiC56pdfbVWo4x06WnJwTjTxsWnqbaw2HSW2DNeE3Tru64n33aH0dF0N7ZyaYvnT_wqgYkQvXn7u0APrf14tTeEMtuxmqLMmrOJpuFGRoNO9XSm5VUu9oRjxm-BbOEcBSbErKrAGke5qRoaee-f1ivKad5weHPEU37gmoWC4-C8qg4xX1nS6ekjCnNYUk8N/s769/About%20Us%20Generator%20%28safelink-aza%29.png" alt="About Us Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our About Us, those changes will be posted here.</em><!-- END of About Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:100px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>About Us</h1>

<p>Welcome to <strong>${nama}</strong>!</p>

<p>${nama} is a platform that provides ${deskripsi}. We are committed to delivering the best services and useful information for our visitors.</p>

<p>This website was founded and managed by <strong>${owner}</strong>. We continuously strive to improve ${nama} to become better and provide the best experience for users.</p>

<h3>Our Mission</h3>
<p>Our mission is to provide high-quality, trustworthy, and easily accessible content for everyone.</p>

<h3>Our Vision</h3>
<p>To become a useful and trusted platform on the internet.</p>

<h3>Contact Us</h3>
<p>If you have any questions, suggestions, or would like to collaborate, please contact us via email at <a href="mailto:${email}">${email}</a>.</p>

<p>Website: <a href="${url}" target="_blank">${url}</a></p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="About Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiC56pdfbVWo4x06WnJwTjTxsWnqbaw2HSW2DNeE3Tru64n33aH0dF0N7ZyaYvnT_wqgYkQvXn7u0APrf14tTeEMtuxmqLMmrOJpuFGRoNO9XSm5VUu9oRjxm-BbOEcBSbErKrAGke5qRoaee-f1ivKad5weHPEU37gmoWC4-C8qg4xX1nS6ekjCnNYUk8N/s769/About%20Us%20Generator%20%28safelink-aza%29.png" border="0" alt="Terms & Conditions Online Approved Site" /></a>
 <em>Should we update, amend or make any changes to our About Us, those changes will be posted here.</em><!-- END of About Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:100px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilAbout").value = hasil;
}

function copyAbout(){
  var teks = document.getElementById("hasilAbout");
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}

// contact
function generateContactTool(){

  var nama    = document.getElementById("namaWeb").value;
  var alamat  = document.getElementById("alamat").value;
  var email   = document.getElementById("emailKontak").value;
  var wa      = document.getElementById("wa").value;
  var jam     = document.getElementById("jam").value;
  var lang    = document.getElementById("contact_language").value;

  let contact = "";

  // =========================
  // INDONESIA
  // =========================
  if(lang === "id"){

    contact = `
<h1>Hubungi Kami</h1>

<p>Jika Anda memiliki pertanyaan, saran, atau ingin bekerja sama dengan <strong>${nama}</strong>, silakan hubungi kami melalui informasi di bawah ini:</p>

<h3>Informasi Kontak</h3>

<ul>
  <li>Email: <a href="mailto:${email}">${email}</a></li>
  <li>WhatsApp: <a href="https://wa.me/${wa}" target="_blank">${wa}</a></li>
  <li>Alamat: ${alamat}</li>
  <li>Jam Operasional: ${jam}</li>
</ul>

<div class="contact-box">

<h3>Kirim Pesan</h3>

<input id="cnama" placeholder="Nama">
<input id="cemail" placeholder="Email">
<textarea id="cpesan" placeholder="Pesan"></textarea>

<button onclick="
window.location.href='mailto:${email}?subject=Pesan dari Website&body='+
'Nama: '+document.getElementById('cnama').value+
'%0AEmail: '+document.getElementById('cemail').value+
'%0A%0APesan:%0A'+
document.getElementById('cpesan').value
">
Kirim
</button>

</div>

<p>Kami akan merespons pesan Anda secepat mungkin. Terima kasih telah menghubungi kami.</p>

<style>
.contact-box{
  max-width:500px;
  margin:30px auto;
  padding:20px;
  border-radius:10px;
  background:#fff;
  box-shadow:0 5px 15px rgba(0,0,0,.1);
}

.contact-box input,
.contact-box textarea{
  width:100%;
  padding:10px;
  margin:10px 0;
  border:1px solid #ddd;
  border-radius:6px;
}

.contact-box button{
  width:100%;
  padding:12px;
  border:none;
  border-radius:6px;
  background:#f39c12;
  color:#fff;
  cursor:pointer;
}
</style>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="Contact Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEholgQamG9SFkW7jHVr62ShxRnoTbhl-KyNt0-9Uw3uc6DO3CodFdNIvJPdTeYWh8qb7AfDZwPk8bHPSxeRD_sNTgx2ohTEXlINXI4IozKlqiiIuL5aQUkoKmzsO2ddRzgPqPUOCMNecanwdjmMv0BUKOkVLVm47lTbpvrNythZ8mE2GiJN9f404JKdXYvw/s744/Contact%20Us%20Generator%20%28safelink-aza%29.png" alt="Contact Us Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Contact Us, those changes will be posted here.</em><!-- END of Contact Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    contact = `
<h1>Contact Us</h1>

<p>If you have any questions, suggestions, or would like to collaborate with <strong>${nama}</strong>, please contact us using the information below:</p>

<h3>Contact Information</h3>

<ul>
  <li>Email: <a href="mailto:${email}">${email}</a></li>
  <li>WhatsApp: <a href="https://wa.me/${wa}" target="_blank">${wa}</a></li>
  <li>Address: ${alamat}</li>
  <li>Operating Hours: ${jam}</li>
</ul>

<div class="contact-box">

<h3>Send Message</h3>

<input id="cnama" placeholder="Your Name">
<input id="cemail" placeholder="Your Email">
<textarea id="cpesan" placeholder="Your Message"></textarea>

<button onclick="
window.location.href='mailto:${email}?subject=Message from Website&body='+
'Name: '+document.getElementById('cnama').value+
'%0AEmail: '+document.getElementById('cemail').value+
'%0A%0AMessage:%0A'+
document.getElementById('cpesan').value
">
Send
</button>

</div>

<p>We will respond to your message as soon as possible. Thank you for contacting us.</p>

<style>
.contact-box{
  max-width:500px;
  margin:30px auto;
  padding:20px;
  border-radius:10px;
  background:#fff;
  box-shadow:0 5px 15px rgba(0,0,0,.1);
}

.contact-box input,
.contact-box textarea{
  width:100%;
  padding:10px;
  margin:10px 0;
  border:1px solid #ddd;
  border-radius:6px;
}

.contact-box button{
  width:100%;
  padding:12px;
  border:none;
  border-radius:6px;
  background:#f39c12;
  color:#fff;
  cursor:pointer;
}
</style>
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/contact-us-generator-online.html" title="Contact Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEholgQamG9SFkW7jHVr62ShxRnoTbhl-KyNt0-9Uw3uc6DO3CodFdNIvJPdTeYWh8qb7AfDZwPk8bHPSxeRD_sNTgx2ohTEXlINXI4IozKlqiiIuL5aQUkoKmzsO2ddRzgPqPUOCMNecanwdjmMv0BUKOkVLVm47lTbpvrNythZ8mE2GiJN9f404JKdXYvw/s744/Contact%20Us%20Generator%20%28safelink-aza%29.png" alt="Contact Us Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Contact Us, those changes will be posted here.</em><!-- END of Contact Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilContact").value = contact;
}

function copyContactTool(){

  var teks = document.getElementById("hasilContact");

  navigator.clipboard.writeText(teks.value);

  alert("Berhasil di copy!");
}

// privasi
function generatePP(){
  var judul = document.getElementById("judul").value;
  var link = document.getElementById("link").value;
  var email = document.getElementById("email").value;

  
var lang  = document.getElementById("pp_language").value;

  let hasil = "";

  // =========================
  // BAHASA INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>Kebijakan Privasi</h1>

<p>Kebijakan Privasi untuk ${judul}</p>

<p>Jika Anda memerlukan informasi lebih lanjut atau memiliki pertanyaan tentang kebijakan privasi kami, silakan hubungi kami melalui email di <a href="mailto:${email}">Privacy</a>.</p>

<p>Di ${link}, kami menganggap privasi pengunjung kami sangat penting. Dokumen kebijakan privasi ini menjelaskan secara rinci jenis informasi pribadi yang dikumpulkan dan dicatat oleh ${link} dan bagaimana kami menggunakannya.</p>

<h3>Berkas Log</h3>
<p>Seperti banyak situs web lainnya, ${link} menggunakan berkas log. Berkas-berkas ini hanya mencatat pengunjung situs - biasanya merupakan prosedur standar bagi perusahaan hosting dan bagian dari analitik layanan hosting. Informasi di dalam berkas log meliputi alamat protokol internet (IP), jenis browser, Penyedia Layanan Internet (ISP), cap tanggal/waktu, halaman rujukan/keluar, dan mungkin jumlah klik. Informasi ini digunakan untuk menganalisis tren, mengelola situs, melacak pergerakan pengguna di situs, dan mengumpulkan informasi demografis. Alamat IP, dan informasi serupa lainnya, tidak dihubungkan dengan informasi apa pun yang dapat diidentifikasi secara pribadi.</p>

<h3>Cookie dan Web Beacon</h3>
<p>${link} menggunakan cookie untuk menyimpan preferensi pengunjung dan menyesuaikan konten.</p>

<h3>Cookie DoubleClick DART</h3>
<li>&#8594; Google, sebagai vendor pihak ketiga, menggunakan cookie untuk menayangkan iklan di ${link}. Google menampilkan iklan berdasarkan kunjungan pengguna.</li>
<li>&#8594; Penggunaan cookie DART oleh Google memungkinkan Google untuk menayangkan iklan kepada pengunjung situs kami berdasarkan kunjungan mereka ke ${link} dan situs lain di Internet.</li>
<li>&#8594; Pengguna dapat menolak penggunaan cookie DART dengan mengunjungi kebijakan privasi jaringan iklan dan konten Google di URL berikut - <a href="https://policies.google.com/technologies/ads" target="_blank">https://policies.google.com/technologies/ads</a></li>

<h3>Mitra Periklanan</h3>
<p>Beberapa mitra periklanan kami mungkin menggunakan cookie dan web beacon di situs kami. Mitra periklanan kami meliputi .......

<li>Google</li>
<li>Adsterra</li>
<li>Monetag</li>
<li>Amazon</li>
<li>Widget Bucks</li>
<li>Adbrite</li>
<li>Clickbank</li>
<li>Linkshare</li>
<li>Jaringan Penerbit Yahoo!</li>
<li>Azoogle</li>
<li>Chitika</li>
<li>Kontera</li>
<li>Lainnya</li>
<p>
Meskipun masing-masing mitra periklanan ini memiliki Kebijakan Privasi sendiri untuk situs mereka, sumber daya yang diperbarui dan terhubung melalui tautan tersedia di sini: <a href="https://safelink-aza.blogspot.com/2026/04/privacy-policy-online-generator.html" target="_blank">Kebijakan Privasi</a> .</p>
<p>
Anda dapat melihat daftar ini untuk menemukan kebijakan privasi untuk setiap mitra periklanan ${link}.
</p>

<p>
Server iklan pihak ketiga atau jaringan iklan ini menggunakan teknologi dalam iklan dan tautan masing-masing yang muncul di ${link}  dan yang dikirim langsung ke browser Anda. Mereka secara otomatis menerima alamat IP Anda ketika ini terjadi. Teknologi lain (seperti cookie, JavaScript, atau Web Beacon) juga dapat digunakan oleh jaringan iklan pihak ketiga situs kami untuk mengukur efektivitas kampanye iklan mereka dan/atau untuk mempersonalisasi konten iklan yang Anda lihat di situs.</p>

<h3>Kebijakan Privasi Pihak Ketiga</h3>
<p>Kami tidak memiliki kontrol atas cookie pihak ketiga. ${link} tidak memiliki akses atau kendali atas cookie yang digunakan oleh pengiklan pihak ketiga.</p>

<p>Jika Anda ingin menonaktifkan cookie, Anda dapat melakukannya melalui opsi peramban Anda masing-masing. Informasi lebih detail tentang pengelolaan cookie dengan peramban web tertentu dapat ditemukan di situs web masing-masing peramban. <a href="https://www.google.com/search?q=apa+itu+cookie&oq=apa+itu+cokie?" target="_blank">Apa Itu Cookie?</a></p>

<h3>Informasi Anak-Anak</h3>
<p>Kami percaya penting untuk memberikan perlindungan tambahan bagi anak-anak secara daring. Kami mendorong orang tua dan wali untuk meluangkan waktu bersama anak-anak mereka secara daring untuk mengamati, berpartisipasi, dan/atau memantau serta membimbing aktivitas daring mereka. </p>
<p>${link} tidak secara sengaja mengumpulkan informasi identitas pribadi apa pun dari anak-anak di bawah usia 13 tahun. Jika orang tua atau wali yakin bahwa situs kami memiliki informasi identitas pribadi anak di bawah usia 13 tahun dalam basis datanya, harap segera hubungi kami (menggunakan kontak di paragraf pertama) dan kami akan melakukan upaya terbaik untuk segera menghapus informasi tersebut dari catatan kami.</p>

<h3>Kebijakan Privasi Online Saja</h3>
<p>Berlaku hanya untuk aktivitas online.</p>

<h3>Persetujuan</h3>
<p>Dengan menggunakan situs ini, Anda menyetujui kebijakan ini.</p>

<h3>Pembaruan</h3>
<p>Kebijakan ini terakhir diperbarui pada: Sabtu, 9 Mei 2026 . Jika kami <a href="" target="_self">memperbarui, mengubah, atau melakukan perubahan apa pun pada kebijakan privasi kami</a>, perubahan tersebut akan diposting di sini.</p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="Privacy Policy Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxPRZ7KL7-Z4LVXd6kjUmLSPT57oX8npQ4VJ4uo1EXb-45VnOYh3G833L47YyQMkCQtDsKytGXTICuP0w2izij9hxXeApWnrQQmlo0uqE-ym4UYIcDN5_-5mqPxo64kwDAmQyWgBjgNZRNUnEwOyj33R7Tyu5TnwqQUuCNa2XJBzIOp6cOySYTTObz7GsZ/s1254/Privacy%20Policy%20Generator%20%28safelink-aza%29.png" alt="Privacy Policy Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Privacy Policy, those changes will be posted here.</em><!-- END of Privacy Policy || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>Privacy Policy</h1>

<p>Privacy Policy for ${judul}</p>

<p>If you require any more information or have any questions about our privacy policy, please feel free to contact us by email at <a href="mailto:${email}">Privacy</a>.</p>

<p>At ${link}, we consider the privacy of our visitors to be extremely important. This privacy policy document describes in detail the types of personal information collected and recorded by ${link} and how we use it.</p>

<h3>Log Files</h3>
<p>Like many other websites, ${link} uses log files. These files merely log visitors to the site - usually a standard procedure for hosting companies and part of hosting services analytics. The information inside the log files includes internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date/time stamp, referring/exit pages, and possibly the number of clicks. This information is used to analyze trends, administer the site, track user movement around the site, and gather demographic information. IP addresses and other such information are not linked to any information that is personally identifiable.</p>

<h3>Cookies and Web Beacons</h3>
<p>${link} uses cookies to store visitors' preferences and customize content.</p>

<h3>DoubleClick DART Cookie</h3>
<li>&#8594; Google, as a third-party vendor, uses cookies to serve ads on ${link}. Google serves ads based on user visits.</li>
<li>&#8594; Google's use of the DART cookie enables it to serve ads to our site's visitors based upon their visit to ${link} and other sites on the Internet.</li>
<li>&#8594; Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy at the following URL - <a href="https://policies.google.com/technologies/ads" target="_blank">https://policies.google.com/technologies/ads</a></li>

<h3>Advertising Partners</h3>
<p>Some of our advertising partners may use cookies and web beacons on our site. Our advertising partners include .......

<li>Google</li>
<li>Adsterra</li>
<li>Monetag</li>
<li>Amazon</li>
<li>Widget Bucks</li>
<li>Adbrite</li>
<li>Clickbank</li>
<li>Linkshare</li>
<li>Yahoo! Publisher Network</li>
<li>Azoogle</li>
<li>Chitika</li>
<li>Kontera</li>
<li>Others</li>
<p>
While each of these advertising partners has their own Privacy Policy for their site, an updated and linked resource is maintained here: <a href="https://safelink-aza.blogspot.com/2026/04/privacy-policy-online-generator.html" target="_blank">Privacy Policies</a> .</p>
<p>
You may consult this listing to find the privacy policy for each of the advertising partners of ${link}.
</p>

<p>
These third-party ad servers or ad networks use technology in their respective advertisements and links that appear on ${link} and which are sent directly to your browser. They automatically receive your IP address when this occurs. Other technologies (such as cookies, JavaScript, or Web Beacons) may also be used by our site's third-party ad networks to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on the site.</p>

<h3>Third Party Privacy Policies</h3>
<p>We have no access to or control over third-party cookies. ${link} has no access to or control over these cookies that are used by third-party advertisers.</p>

<p>If you wish to disable cookies, you may do so through your individual browser options. More detailed information about cookie management with specific web browsers can be found at the browsers' respective websites. <a href="https://www.google.com/search?q=what+is+cookie?" target="_blank">What Are Cookies?</a></p>

<h3>Children's Information</h3>
<p>We believe it is important to provide added protection for children online. We encourage parents and guardians to spend time online with their children to observe, participate in, and/or monitor and guide their online activity. </p>
<p>${link} does not knowingly collect any personally identifiable information from children under the age of 13. If a parent or guardian believes that our site has personally identifiable information of a child under the age of 13 in its database, please contact us immediately (using the contact information in the first paragraph) and we will use our best efforts to promptly remove such information from our records.</p>

<h3>Online Privacy Policy Only</h3>
<p>Applicable only to online activities.</p>

<h3>Consent</h3>
<p>By using this site, you consent to this policy.</p>

<h3>Updates</h3>
<p>This policy was last updated on: Saturday, May 9, 2026 .
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/privacy-policy-online-generator.html" title="Privacy Policy Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxPRZ7KL7-Z4LVXd6kjUmLSPT57oX8npQ4VJ4uo1EXb-45VnOYh3G833L47YyQMkCQtDsKytGXTICuP0w2izij9hxXeApWnrQQmlo0uqE-ym4UYIcDN5_-5mqPxo64kwDAmQyWgBjgNZRNUnEwOyj33R7Tyu5TnwqQUuCNa2XJBzIOp6cOySYTTObz7GsZ/s1254/Privacy%20Policy%20Generator%20%28safelink-aza%29.png" alt="Privacy Policy Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Privacy Policy, those changes will be posted here.</em><!-- END of Privacy Policy || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasil").value = hasil;
}

function copyPP(){
  var teks = document.getElementById("hasil");
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}

//disclaimer
function generateDisclaimer(){

  var nama = document.getElementById("d_siteName").value;
  var url  = document.getElementById("d_siteUrl").value;
  var lang = document.getElementById("language").value;

  let disclaimer = "";

  // =========================
  // INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

disclaimer = `

<h1>Disclaimer untuk ${nama}</h1>

<p>Semua informasi di situs web ini - ${url} - dipublikasikan dengan itikad baik dan hanya untuk tujuan informasi umum. ${nama} tidak memberikan jaminan apa pun tentang kelengkapan, keandalan, dan keakuratan informasi ini.</p>

<p>Segala tindakan yang Anda lakukan atas informasi yang Anda temukan di situs ini sepenuhnya merupakan risiko Anda sendiri. ${nama} tidak akan bertanggung jawab atas kerugian dan/atau kerusakan sehubungan dengan penggunaan situs kami.</p>

<p>Dari situs kami, Anda dapat mengunjungi situs lain melalui tautan. Kami tidak memiliki kontrol atas konten situs tersebut.</p>

<p>Persetujuan: Dengan menggunakan situs kami, Anda menyetujui disclaimer ini.</p>

<p>Pembaruan: ${tanggal}</p>


<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/disclaimer-terms-conditions-online.html" title="Disclaimer Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKVZp2HqvCISALHei7LzHM_0sQdNc-WrAGnRvK6cZCUYwGIIntnCAjEZybmh7ov4OsXbiYBnCHvauT1kdPRIt89ixlsy8x3M9W1yyLB8LWgbBVd59r7ffx2r4L3pe9kH30xKX4qw6VHgH6o2pMlsxGlgT_9XpTIfJojnjPl4-tId1FvKcV-O3mtjbgwTXA/s1505/Disclaimer%20Online%20Generator%20%28safelink-aza%29.png" alt="Disclaimer Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Disclaimer, those changes will be posted here.</em><!-- END of Disclaimer || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:105px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

disclaimer = `
<h1>Disclaimer for ${nama}</h1>

<p>All information on this website - ${url} - is published in good faith and for general informational purposes only. ${nama} makes no warranties regarding the completeness, reliability, and accuracy of this information.</p>

<p>Any action you take based on the information you find on this website is strictly at your own risk. ${nama} will not be liable for any losses and/or damages in connection with the use of our website.</p>

<p>From our website, you may visit other websites through external links. We have no control over the content of those sites.</p>

<p>Consent: By using our website, you hereby consent to this disclaimer.</p>

<p>Update: ${tanggal}</p>

<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/disclaimer-terms-conditions-online.html" title="Disclaimer Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKVZp2HqvCISALHei7LzHM_0sQdNc-WrAGnRvK6cZCUYwGIIntnCAjEZybmh7ov4OsXbiYBnCHvauT1kdPRIt89ixlsy8x3M9W1yyLB8LWgbBVd59r7ffx2r4L3pe9kH30xKX4qw6VHgH6o2pMlsxGlgT_9XpTIfJojnjPl4-tId1FvKcV-O3mtjbgwTXA/s1505/Disclaimer%20Online%20Generator%20%28safelink-aza%29.png" alt="Disclaimer Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Disclaimer, those changes will be posted here.</em><!-- END of Disclaimer || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:105px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilDisclaimer").value = disclaimer;
}

function copyText(id){
  var teks = document.getElementById(id);
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}

// terms
function generateTerms(){

  var nama  = document.getElementById("t_siteName").value;
  var url   = document.getElementById("t_siteUrl").value;
  var email = document.getElementById("t_siteEmail").value;
  var lang  = document.getElementById("terms_language").value;

  let terms = "";

  // =========================
  // BAHASA INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

terms = `
<h1>Syarat & Ketentuan ${nama}</h1>

  <p>Selamat datang di situs <strong>${nama}</strong>.</p>

  <p>
    Syarat dan ketentuan ini menjelaskan aturan serta ketentuan penggunaan
    situs web yang beralamat di <strong>${url}</strong>.
  </p>

  <p>
    Dengan mengakses situs web ini, Anda dianggap telah memahami dan menyetujui
    seluruh syarat dan ketentuan yang berlaku. Jika Anda tidak menyetujui salah
    satu bagian dari syarat dan ketentuan ini, mohon untuk tidak melanjutkan
    penggunaan situs web ini.
  </p>

  <h3>Definisi</h3>

  <p>
    Dalam dokumen ini, istilah &#8220;Klien&#8221;, &#8220;Anda&#8221;, dan &#8220;Pengguna&#8221; merujuk kepada
    pihak yang mengakses situs web ini. Istilah &#8220;Kami&#8221;, &#8220;Kita&#8221;, dan
    &#8220;Perusahaan&#8221; merujuk kepada pengelola situs web ini. Sedangkan istilah
    &#8220;Pihak&#8221; mengacu kepada pengguna dan pengelola situs secara bersama-sama.
  </p>

  <h3>Cookie</h3>

  <p>
    Situs web ini menggunakan cookie untuk meningkatkan pengalaman pengguna.
    Dengan mengakses situs ini, Anda menyetujui penggunaan cookie sesuai dengan
    Kebijakan Privasi yang berlaku.
  </p>

  <p>
    Cookie digunakan untuk mengaktifkan fitur tertentu dan membantu kami
    memahami aktivitas pengguna di situs web. Beberapa mitra periklanan atau
    afiliasi kami juga dapat menggunakan cookie.
  </p>

  <h3>Lisensi</h3>

  <p>
    Kecuali dinyatakan lain, seluruh hak kekayaan intelektual atas materi yang
    terdapat di situs <strong>${url}</strong> dimiliki oleh kami dan/atau
    pemberi lisensi kami. Semua hak dilindungi oleh undang-undang yang berlaku.
  </p>

  <p>Anda diperbolehkan mengakses situs ini untuk penggunaan pribadi dengan ketentuan berikut:</p>

  <ul>
    <li>Dilarang mempublikasikan ulang materi dari situs ini.</li>
    <li>Dilarang menjual, menyewakan, atau memberikan sub-lisensi materi situs.</li>
    <li>Dilarang menyalin atau menggandakan konten situs tanpa izin.</li>
    <li>Dilarang mendistribusikan ulang konten dari situs ini.</li>
  </ul>

  <h3>Komentar Pengguna</h3>

  <p>
    Beberapa bagian situs ini memungkinkan pengguna untuk memposting komentar
    dan bertukar informasi. Kami tidak menyaring, mengedit, atau meninjau
    komentar sebelum ditampilkan di situs web.
  </p>

  <p>
    Komentar yang dipublikasikan sepenuhnya merupakan tanggung jawab masing-masing
    pengguna dan tidak mencerminkan pandangan kami.
  </p>

  <p>Dengan memposting komentar, Anda menyatakan bahwa:</p>

  <ul>
    <li>Anda memiliki hak untuk mempublikasikan komentar tersebut.</li>
    <li>Komentar tidak melanggar hak cipta, merek dagang, atau hak pihak lain.</li>
    <li>Komentar tidak mengandung unsur fitnah, pornografi, atau tindakan melanggar hukum.</li>
    <li>Komentar tidak digunakan untuk spam atau promosi ilegal.</li>
  </ul>

  <p>
    Kami berhak menghapus komentar yang dianggap tidak pantas atau melanggar
    syarat dan ketentuan ini.
  </p>

  <h3>Tautan ke Situs Kami</h3>

  <p>
    Organisasi tertentu seperti instansi pemerintah, mesin pencari, media
    berita, dan direktori online diperbolehkan menautkan ke situs kami tanpa
    izin tertulis sebelumnya.
  </p>

  <p>
    Kami juga dapat mempertimbangkan permintaan tautan dari organisasi lain
    apabila dinilai sesuai dan tidak merugikan pihak mana pun.
  </p>

  <h3>iFrame</h3>

  <p>
    Tanpa izin tertulis dari kami, Anda tidak diperbolehkan membuat frame atau
    tampilan lain yang mengubah visual situs web kami.
  </p>

  <h3>Tanggung Jawab Konten</h3>

  <p>
    Kami tidak bertanggung jawab atas konten yang muncul di situs web pihak
    ketiga yang menautkan ke situs kami. Anda setuju untuk melindungi kami dari
    segala klaim yang timbul akibat konten di situs Anda.
  </p>

  <h3>Reservasi Hak</h3>

  <p>
    Kami berhak meminta penghapusan tautan ke situs kami kapan saja. Kami juga
    berhak mengubah syarat dan ketentuan ini sewaktu-waktu tanpa pemberitahuan
    sebelumnya.
  </p>

  <h3>Penghapusan Tautan</h3>

  <p>
    Jika Anda menemukan tautan di situs kami yang dianggap tidak pantas, Anda
    dapat menghubungi kami. Kami akan mempertimbangkan permintaan tersebut,
    namun tidak berkewajiban untuk menghapusnya.
  </p>

  <h3>Penafian</h3>

  <p>
    Kami tidak menjamin bahwa seluruh informasi di situs ini selalu akurat,
    lengkap, atau terbaru. Semua layanan dan informasi disediakan &#8220;sebagaimana
    adanya&#8221;.
  </p>

  <p>
    Sejauh diizinkan oleh hukum yang berlaku, kami tidak bertanggung jawab atas
    kerugian atau kerusakan apa pun yang timbul akibat penggunaan situs web ini.
  </p>

  <p>
    Selama situs web ini tersedia secara gratis, kami tidak bertanggung jawab
    atas kehilangan data, gangguan layanan, atau kerusakan lainnya yang mungkin
    terjadi akibat penggunaan situs ini.
  </p>

<h3>Kontak</h3>
<p>Email: ${email}</p>

<p>Terakhir diperbarui: ${tanggal}</p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/2026/04/terms-conditions-online-generator.html" title="Terms & Conditions Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgscU8KF9hECAtS54LLsRQFQCweDLwFcG1zT5SmTIUTurZSpJRicb7qsJY5MHkIEAqNCEALyHDYOkh3epd69wOotup6kGm9hgQqt4FFEYQv0zIv4FTjjsU_7D7nX1isMDMxydnB08Cwie0CRMTG8RPA80Sg8Z0Gxjxvug4b_urBk4Y_WauOJZmoq4QSR6Ya/s1505/Terms%20&%20Conditions%20Online%20Generator%20%28safelink-aza%29.png" alt="Terms & Conditions Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Terms & Conditions, those changes will be posted here.</em><!-- END of Terms & Conditions || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

terms = `
<h1>Terms & Conditions ${nama}</h1>

<p>Welcome to <strong>${nama}</strong>!</p><br/>

<p>These terms and conditions outline the rules and regulations for the use of <strong>this web</strong>'s Website, located at <strong>${url}</strong></p><br/>

<p>By accessing this website we assume you accept these terms and conditions. Do not continue to use <strong>this web</strong> if you do not agree to take all of the terms and conditions stated on this page.</p><br/>

<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company&#8217;s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client&#8217;s needs in respect of provision of the Company&#8217;s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p><br/>

<h3><strong>Cookies</strong></h3>

<p>We employ the use of cookies. By accessing <strong>this web</strong>, you agreed to use cookies in agreement with the <strong>this web</strong>'s Privacy Policy.</p><br/>

<p>Most interactive websites use cookies to let us retrieve the user&#8217;s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p><br/>

<h3><strong>License</strong></h3>

<p>Unless otherwise stated, <strong>this web</strong> and/or its licensors own the intellectual property rights for all material on <strong>this web</strong>. All intellectual property rights are reserved. You may access this from <strong>this web</strong> for your own personal use subjected to restrictions set in these terms and conditions.</p><br/>

<p>You must not:</p><br/>

<ul>

	<li>Republish material from <strong>this web</strong></li>

	<li>Sell, rent or sub-license material from <strong>this web</strong></li>

	<li>Reproduce, duplicate or copy material from <strong>this web</strong></li>

	<li>Redistribute content from <strong>this web</strong></li>

</ul>

<p>This Agreement shall begin on the date hereof.</p><br/>

<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. <strong>this web</strong> does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of <strong>this web</strong>,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, <strong>this web</strong> shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p><br/>

<p><strong>this web</strong> reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p><br/>

<p>You warrant and represent that:</p><br/>

<ul>

	<li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>

	<li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>

	<li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>

	<li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>

</ul>

<p>You hereby grant <strong>this web</strong> a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p><br/>

<h3><strong>Hyperlinking to our Content</strong></h3>

<p>The following organizations may link to our Website without prior written approval:</p><br/>

<ul>

	<li>Government agencies;</li>

	<li>Search engines;</li>

	<li>News organizations;</li>

	<li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>

	<li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>

</ul>

<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party&#8217;s site.</p><br/>

<p>We may consider and approve other link requests from the following types of organizations:</p><br/>

<ul>

	<li>commonly-known consumer and/or business information sources;</li>

	<li>dot.com community sites;</li>

	<li>associations or other groups representing charities;</li>

	<li>online directory distributors;</li>

	<li>internet portals;</li>

	<li>accounting, law and consulting firms; and</li>

	<li>educational institutions and trade associations.</li>

</ul>

<p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of <strong>this web</strong>; and (d) the link is in the context of general resource information.</p><br/>

<p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party&#8217;s site.</p><br/>

<p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to <strong>this web</strong>. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p><br/>

<p>Approved organizations may hyperlink to our Website as follows:</p><br/>

<ul>

	<li>By use of our corporate name; or</li>

	<li>By use of the uniform resource locator being linked to; or</li>

	<li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party&#8217;s site.</li>

</ul>

<p>No use of <strong>this web</strong>'s logo or other artwork will be allowed for linking absent a trademark license agreement.</p><br/>

<h3><strong>iFrames</strong></h3>

<p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p><br/>

<h3><strong>Content Liability</strong></h3>

<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p><br/>

<h3><strong>Reservation of Rights</strong></h3>

<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it&#8217;s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p><br/>

<h3><strong>Removal of links from our website</strong></h3>

<p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p><br/>

<p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p><br/>

<h3><strong>Disclaimer</strong></h3>

<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p><br/>

<ul>

	<li>limit or exclude our or your liability for death or personal injury;</li>

	<li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>

	<li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>

	<li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>

</ul>

<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p><br/>

<p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>

<h3>Contact</h3>
<p>Email: ${email}</p>

<p>Last updated: ${tanggal}</p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="Terms & Conditions Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-CiapLCqwcPwt4LQnBvO-W1tSXSMmIkQl5e-axQltZDhCz_owIFgCtv5sS1fm7c3WvveANEs2IDm2j7mFkiomKeMKx7Jftez7zARJ8-eAzBO6x4wc-EDolw8Hsm6BGhBAH2yLqLCofnKkDF6C7GZ4lYfox3nPNSiufcgbhc-gvyqWRZlauoF4l67V-EFS/s1024/Terms%20&%20Conditions%20Generator%20%28Safelink-aza%29.png" alt="Terms & Conditions Online Approved Site" /></a>
 <em>Should we update, amend or make any changes to our Terms & Conditions, those changes will be posted here.</em><!-- END of Terms & Conditions || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilTerms").value = terms;
}

function copyText(id){
  var teks = document.getElementById(id);
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}

// dmca
function generateDmca(){

  var nama  = document.getElementById("dmca_siteName").value;
  var url   = document.getElementById("dmca_siteUrl").value;
  var email = document.getElementById("dmca_siteEmail").value;
  var lang  = document.getElementById("dmca_language").value;

  let dmca = "";

  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

dmca = `
<div class="legal-page">
  <h1>DMCA Policy</h1>

  <p>Di perbaharui pada: <strong>${tanggal}</strong></p>

  <p>
    Website ini (<strong>${nama}</strong>) menghormati hak kekayaan intelektual orang lain dan mematuhi ketentuan
    <em>Digital Millennium Copyright Act (DMCA)</em>.
  </p>

  <h2>1. Hak Cipta</h2>
  <p>
    Semua konten yang ditampilkan di situs ini dibuat untuk tujuan informasi, edukasi, dan referensi.
    Kami tidak bermaksud melanggar hak cipta pihak mana pun.
  </p>

  <h2>2. Laporan Pelanggaran</h2>
  <p>
    Jika Anda adalah pemilik hak cipta dan menemukan konten yang melanggar di situs ini,
    silakan hubungi kami dengan informasi berikut:
  </p>

  <ul>
    <li>Bukti kepemilikan konten</li>
    <li>URL konten yang dilanggar (<b>Contoh</b>: <em>${url}/2026/12/konten-hak-cipta.html</em></li>
    <li>Kontak email Anda</li>
  </ul>

  <h2>3. Tindakan Kami</h2>
  <p>
    Kami akan segera meninjau laporan Anda dan menghapus konten yang terbukti melanggar hak cipta
    dalam waktu yang wajar.
  </p>

  <h2>4. Kontak DMCA</h2>
  <p>Email: <strong>${email}</strong></p>
  <p>Halaman Kontak: <a href="${url}/p/contact.html" target="_blank">${url}/p/contact.html</a>
</div>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="DMCA Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEidAHSfQuQsoDRzriXtZUY-vmYG-bYF9a8duFPf8-ZYSO4bToZe75hQLcZgpSFRHjq6409lXgjH7jz2sVSCZQCRfJvrFo_8U3TuO2nLEr1Wrbo7N2XFViRM8fQoiP_Yy3QtGxdWu0kxHiye8Zr8GejFQxs-BsUmXVkqMxVIPi3REr4pFhOOrB41vftXhair/s1536/DMCA%20Generator%28safelink-aza%29.png" alt="DMCA Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our DMCA Policy, those changes will be posted here.</em><!-- END of DMCA || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

dmca = `
<h1>DMCA Policy</h1>

  <p>Last updated: <strong>${tanggal}</strong></p>

  <p>
    This website (<strong>${nama}</strong>) respects the intellectual property rights of others and complies with the
    provisions of the <em>Digital Millennium Copyright Act (DMCA)</em>.
  </p>

  <h2>1. Copyright</h2>
  <p>
    All content displayed on this website is created for informational, educational, and reference purposes.
    We do not intend to infringe any copyrighted material belonging to any party.
  </p>

  <h2>2. Copyright Infringement Report</h2>
  <p>
    If you are a copyright owner and believe that any content on this website infringes your rights,
    please contact us with the following information:
  </p>

  <ul>
    <li>Proof of ownership of the content</li>
    <li>URL of the infringing content (<b>Example</b>: <em>${url}/2026/12/content-copyright.html</em></li>
    <li>Your contact email address</li>
  </ul>

  <h2>3. Our Actions</h2>
  <p>
    We will promptly review your complaint and remove any content proven to violate copyright
    within a reasonable time frame.
  </p>

  <h2>4. DMCA Contact</h2>
  <p>Email: <strong>${email}</strong></p>
  <p>Contact Page: <a href="${url}/p/contact.html" target="_blank">${url}/p/contact.html</a>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/2026/05/dmca-policy-generator.html" title="DMCA Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEidAHSfQuQsoDRzriXtZUY-vmYG-bYF9a8duFPf8-ZYSO4bToZe75hQLcZgpSFRHjq6409lXgjH7jz2sVSCZQCRfJvrFo_8U3TuO2nLEr1Wrbo7N2XFViRM8fQoiP_Yy3QtGxdWu0kxHiye8Zr8GejFQxs-BsUmXVkqMxVIPi3REr4pFhOOrB41vftXhair/s1536/DMCA%20Generator%28safelink-aza%29.png" alt="DMCA Online Approved Site" /></a>
 <em>Should we update, amend or make any changes to our DMCA Policy, those changes will be posted here.</em><!-- END of DMCA || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilDmca").value = dmca;
}

function copyText(id){
  var teks = document.getElementById(id);
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}

// parse
const encryptedCreatorName = "QXlp";
  function verifyCreator() {
    const storedCreator = localStorage.getItem('creatorHash');
    if (storedCreator !== encryptedCreatorName) {
      alert("Nama pembuat telah diubah! Script tidak akan berfungsi.");
      return false;
    }
    return true;
  }

  function convert() {
    if (!verifyCreator()) return;

    var ele1 = document.getElementById("somewhere");
    var replaced = ele1.value;
    replaced = replaced.replace(/&/ig, "&amp;");
    replaced = replaced.replace(/</ig, "&lt;");
    replaced = replaced.replace(/>/ig, "&gt;");
    replaced = replaced.replace(/"/ig, "&quot;");
    replaced = replaced.replace(/&#177;/ig, "&plusmn;");
    replaced = replaced.replace(/&#169;/ig, "&copy;");
    replaced = replaced.replace(/&#174;/ig, "&reg;");
    replaced = replaced.replace(/ya'll/ig, "ya'll");
    ele1.value = replaced;
  }

  // Fungsi untuk select all dan copy
  function selectAllAndCopy() {
    var textarea = document.getElementById("somewhere");
    textarea.select();
    textarea.setSelectionRange(0, 99999); // Untuk mobile
    document.execCommand("copy");

    alert("Teks berhasil disalin!");
  }

  if (!localStorage.getItem('creatorHash')) {
    localStorage.setItem('creatorHash', encryptedCreatorName);
  }
  // all
  document.addEventListener("DOMContentLoaded", function () {

  const tools = [
    "encrypt",
    "marketplace",
    "about-us",
    "contact-us",
    "privacy-policy",
    "disclaimer",
    "terms",
    "dmca",
    "box",
    "parse"
  ];

  const titles = {
    "encrypt": "Encrypt HTML",
    "marketplace": "Marketplace Generator",
    "about-us": "About Us",
    "contact-us": "Contact Us",
    "privacy-policy": "Privacy Policy",
    "disclaimer": "Disclaimer",
    "terms": "Terms & Conditions",
    "dmca": "DMCA",
    "box": "Box Copy",
    "parse": "Parse/Escape HTML"
  };

  const params = new URLSearchParams(window.location.search);
  const current = params.get("id");

  // sembunyikan semua content
  tools.forEach(id => {
    const el = document.getElementById(id);
    if(el) el.style.display = "none";
  });

  // kalau belum pilih tool
  if(!current || !tools.includes(current)){
    
    document.getElementById("welcome-page").style.display = "block";
    document.getElementById("toolNav").style.display = "none";

    return;
  }

  // sembunyikan welcome
  document.getElementById("welcome-page").style.display = "none";

  // tampilkan content
  const active = document.getElementById(current);
  if(active){
    active.style.display = "block";
  }

  // tampilkan nav
  document.getElementById("toolNav").style.display = "flex";

  // title
  document.title = titles[current] + " - Tool";

  // index
  const index = tools.indexOf(current);

  // prev next
  const prev = tools[(index - 1 + tools.length) % tools.length];
  const next = tools[(index + 1) % tools.length];

  // tombol
  document.getElementById("prevBtn").href = "?id=" + prev;
  document.getElementById("nextBtn").href = "?id=" + next;

});

// lonceng
const counters = document.querySelectorAll('.counter');

counters.forEach(counter=>{

let target = +counter.getAttribute('data-target');
let count = 0;

function updateCounter(){

let increment = target / 100;

count += increment;

if(count < target){

counter.innerText =
Math.floor(count).toLocaleString() + '+';

requestAnimationFrame(updateCounter);

}else{

counter.innerText =
target.toLocaleString() + '+';

}

}

updateCounter();

});
// popular
function renderPopular(data){

  let posts = data.feed.entry;
  let html = "";

  posts.forEach(post => {

    let title = post.title.$t;
    let link = post.link.find(l => l.rel === "alternate").href;

    let img = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjIIPWic-Vz1x3CVqd7QYVeD4_GW-w_4RMKA00AKHvTGrCgdH2xTKKaPQASQXuyzbc0880Kuo9aRG24K9DskTDpkiVJ4zIkza4V07rOi_OLXjApwUv_8gwS9Z-dfgsJOSpP2gKO3wqyqB62KOD7Blg12eK82jNga3HYxWO588URinbmgkgEYoumIovh5Vs/s1254/No%20Image%20%28Mang%20Ayi%20Service%29.png";

    if(post.media$thumbnail){
      img = post.media$thumbnail.url.replace("s72-c","s100-c");
    }

    html += `
      <a class="pop-item" href="${link}">
        <img src="${img}" loading="lazy">
        <span>${title}</span>
      </a>
    `;
  });

  document.getElementById("popular").innerHTML = html;
}

// toast
(function(){

  window.alert = function(message){

    const oldToast = document.querySelector(".modern-alert-toast");

    if(oldToast){
      oldToast.remove();
    }

    const toast = document.createElement("div");

    toast.className = "modern-alert-toast";

    toast.innerHTML = `
      <div style='         display:flex;         align-items:center;         gap:8px;       '>
        <span>&#9889;</span>
        <span>${message}</span>
      </div>
    `;

    toast.style.position = "fixed";
    toast.style.left = "50%";
    toast.style.bottom = "50px";
    toast.style.transform = "translateX(-50%)";
    toast.style.background = "rgba(0,0,0,.88)";
    toast.style.color = "#fff";
    toast.style.padding = "12px 18px";
    toast.style.borderRadius = "14px";
    toast.style.fontSize = "14px";
    toast.style.fontFamily = "Arial,sans-serif";
    toast.style.zIndex = "999999";
    toast.style.opacity = "0";
    toast.style.transition = ".3s";
    toast.style.maxWidth = "90%";
    toast.style.backdropFilter = "blur(6px)";
    toast.style.boxShadow = "0 8px 25px rgba(0,0,0,.2)";

    document.body.appendChild(toast);

    setTimeout(() => {

      toast.style.opacity = "1";
      toast.style.bottom = "30px";

    },10);

    setTimeout(() => {

      toast.style.opacity = "0";
      toast.style.bottom = "20px";

      setTimeout(() => {

        toast.remove();

      },300);

    },5500);

  };

})();